In [1]:
import pandas as pd
df = pd.read_csv("chickwts.csv")

In [2]:
df.head()

   Unnamed: 0  weight       feed
0           1     179  horsebean
1           2     160  horsebean
2           3     136  horsebean
3           4     227  horsebean
4           5     217  horsebean

In [3]:
df.groupby("feed")["weight"].agg(["min", "mean", "max"])

           min        mean  max
feed
casein     216  323.583333  404
horsebean  108  160.200000  227
linseed    141  218.750000  309
meatmeal   153  276.909091  380
soybean    158  246.428571  329
sunflower  226  328.916667  423

Sunflower is the correst choice. It has highest min, mean, and max. Soybean is often cheaper. Along with corn, it is also industry standard, but weight is the priority and sunflower feed produces the largest chickens across the board. Soybean ranks 3rd for min and 4th for mean and max.